//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_S2016_Lesson6B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Europe
    {
        public int GameID { get; set; }
        public string Title { get; set; }
        public System.DateTime DateOfGame { get; set; }
        public string Description { get; set; }
        public int TotalHome { get; set; }
        public int TotalAway { get; set; }
        public int Spectators { get; set; }
        public string WinningTeam { get; set; }
    }
}
