//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_S2016_Lesson6B.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnect : DbContext
    {
        public DefaultConnect()
            : base("name=DefaultConnect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asia> Asias { get; set; }
        public virtual DbSet<Europe> Europes { get; set; }
        public virtual DbSet<NorthAmerica> NorthAmericas { get; set; }
        public virtual DbSet<SouthAmerica> SouthAmericas { get; set; }
    }
}
